accept-transfers:
  default: "false"
  description: "是否接受来自其他服务器使用传输命令/数据包的传输。如果设置为 false，服务器将断开客户端的连接"
allow-flight:
  default: "false"
  description: "是否允许玩家在生存模式中开启飞行的时候不踢出玩家。这种情况很可能是通过作弊实现的，但也可能会出现误判"
allow-nether:
  default: "true"
  description: "是否开启下界维度生成。大厅，游戏等不需要下界的子服可以直接关闭"
broadcast-console-to-ops:
  default: "true"
  description: "是否将控制台命令输出发送给所有在线的管理员"
broadcast-rcon-to-ops:
  default: "true"
  description: "是否将 RCON 命令输出发送给所有在线的管理员"
bug-report-link:
  default: ""
  description: "设置一个用于客户端菜单中“报告服务器错误”按钮的 URL 值"
debug:
  default: "false"
  description: "是否启用服务器的调试（debug）模式"
difficulty:
  default: "easy"
  description: '设置定义服务器的难度。（允许的值：“peaceful（和平）”、“easy（简单）”、“normal（普通）”、“hard（困难）”）'
enable-command-block:
  default: "true"
  description: "是否开启命令方块，玩家获取方块仍然需要 OP 权限"
enable-jmx-monitoring:
  default: "false"
  description: >
    是否启用 JMX 监控
    公开一个对象名称为 “net.minecraft.server:type=Server” 的 MBean（管理构件），
    以及 “averageTickTime”（平均滴答时间）和 “tickTimes”（滴答次数）这两个属性，以毫秒为单位展示滴答时间。
    为了在 Java 运行时启用 JMX，你需要在启动时添加一些 JVM 参数，具体参数和配置方法可以参考 [Oracle 官方文档](https://docs.oracle.com/javase/8/docs/technotes/guides/management/agent.html)
enable-query:
  default: "false"
  description: "是否启用 GameSpy4 协议服务器监听器。用于获取服务器的信息"
enable-rcon:
  default: "false"
  description: "是否启用 RCON 允许对服务器控制台的远程访问"
enable-status:
  default: "true"
  description: >
    是否启用用于获取服务器信息的监听器，使服务器出现在服务器列表中。如果关闭此功能，服务器将显示为离线状态，但玩家仍然可以连接。
    子服状态下可以关闭以节省带宽，客户端获取状态直接由反代理端（velocity/waterfall/BungeeCord）响应
enforce-secure-profile:
  default: "true"
  description: "是否启用 Mojang 公钥验证，没有 Mojang 签名的公钥的玩家将无法连接到服务器"
enforce-whitelist:
  default: "false"
  description: "是否启用白名单功能，启用后只有 white-list 内的玩家才能连接到服务器"
entity-broadcast-range-percentage:
  default: "100"
  description: >
    设置向客户端发送的实体渲染距离，较高的值意味着它们可以从更远的地方被渲染，可能会导致更多的延迟。
    这模仿了客户端视频设置中的功能（与渲染距离类似，只要在服务器设置之下，客户端可以自定义）。这必须在10%到1000%之间
force-gamemode:
  default: "false"
  description: >
    是否强制玩家以默认游戏模式加入。这将在他们重新连接时重置他们之前的游戏模式
function-permission-level:
  default: "2"
  description: "设置函数的默认权限级别。（允许的值：1、2、3、4）"
gamemode:
  default: "survival"
  description: '设置玩家加入服务器的默认游戏模式。（允许的值：“survival（生存）”、“creative（创造）”、“adventure（冒险）”、“spectator（旁观者）”）'
generate-structures:
  default: "true"
  description: "是否允许生成结构（如村庄），由于地牢和沙漠水井在技术上属于地物，因而即使此项设为 false，其仍然会生成"
generator-settings:
  default: "{}"
  description: >-
    设置用于自定义世界生成的设置。需要遵循[其格式](https://minecraft.wiki/w/Java_Edition_level_format#generatorOptions_tag_format)并编写相应的 JSON 字符串。
    例如：{"layers"\:[{"height"\:1,"block"\:"minecraft\:air"}],"lakes"\:false,"features"\:false,"biome"\:"minecraft\:the_void","structure_overrides"\:[]}
hardcore:
  default: "false"
  description: "是否开启硬核模式，如果设置为 true，玩家死亡后将被设置为旁观者模式"
hide-online-players:
  default: "false"
  description: "是否在客户端请求数据包时隐藏数据包中的发送的玩家列表"
initial-disabled-packs:
  default: ""
  description: "设置在创建世界时不会自动启用的数据包列表，用英文逗号（,）分隔列表"
initial-enabled-packs:
  default: "vanilla"
  description: "设置在创建世界时需要启用的数据包列表，用英文逗号（,）分隔列表。一些功能包需要明确启用"
level-name:
  default: "world"
  description: "设置默认的世界名称，这也是保存世界数据的文件夹的名称"
level-seed:
  default: ""
  description: "设置用于生成世界的种子，留空则默认为随机。部分服务端会有更大的种子计算方式，列如：1024 位的种子生成规则"
level-type:
  default: "minecraft:normal"
  description: 设置世界生成器的类型。（允许的值：`"normal（默认）"`、`"flat（超平坦）"`、`"large_biomes（巨型生物群系）"`、`"amplified（放大化）"`、`"single_biome_surface（单一生物群系）"`、`"buffet"`、`"default_1_1"`、`"customized（自定义）"`）
log-ips:
  default: "true"
  description: >-
    服务端是否应该记录客户端的 IP 地址。
    这不会和记录客户端 IP 地址的插件冲突。
max-chained-neighbor-updates:
  default: "1000000"
  description: >
    在跳过后续更新之前限制连续邻近更新的次数。
    设置为负以禁用。
max-players:
  default: "20"
  description: "允许同时在线的最大玩家数量。"
max-tick-time:
  default: "60000"
  description: >
    在监视进程强制杀死服务器进程之间，每个游戏刻最大可运算的时间，单位为毫秒。
    如果服务器在此时间内未完成处理一个游戏刻，监视进程将认为服务器已崩溃，并通过调用 System.exit(1) 强制关闭服务器。
    如果设置为 -1，则禁用此功能。
max-world-size:
  default: "29999984"
  description: >
    最大允许的世界半径，单位为一个方块。
    这只会影响创建世界时的世界大小，而不是世界边界大小。(世界边界大小为 29999984)
motd:
  default: "A Minecraft Server"
  description: "服务器今日信息。这将显示在服务器列表中。"
network-compression-threshold:
  default: "256"
  description: "超过该数值的数据包将被压缩，单位为字节。设置为负数以禁用压缩。"
online-mode:
  default: "true"
  description: >
    如果设置为 true，那么服务端将强制将客户端所使用的账号与 Minecraft 认证服务器上的数据进行比对。
    这将防止离线玩家进入服务器。
op-permission-level:
  default: "4"
  description: "玩家被赋予管理员权限时，该玩家可以执行的命令的最大等级。 (可设定值为 0, 1, 2, 3, 4)"
pause-when-empty-seconds:
  vanilla: "60"
  default: "-1"
  description: >
    当服务器内没有玩家时候，经过多少秒后停止服务器。
    默认禁用，因为其与某些在玩家下线时有额外行为，比如空闲时进行数据处理的插件不兼容。
player-idle-timeout:
  default: "0"
  description: >
    如果此项为非零整数，那么服务器将会在玩家挂机超过指定的分钟数后将其踢出服务器。(默认为 0)
    客户端如若发送以下的数据包，将会停止该计时器:
    "点击活版门"，"物品附魔"，"更新告示牌文字"，"挖掘方块"，"放置方块"，"改变手持物品"，"甩手动作"，"实体动作"，
    "客户端状态"，"发送信息"，"右键实体"。
prevent-proxy-connections:
  default: "false"
  description: >
    如果服务器发送的 ISP/AS 与 Mojang Studios 身份验证服务器的 ISP/AS 不同，则玩家将无法加入服务器。
pvp:
  default: "true"
  description: "如果设置为 false，那么玩家将无法互相攻击。"
query.port:
  default: "25565"
  description: ""
rate-limit:
  default: "0"
  description: >
    客户端最大发包数量。超过该阈值将被踢出。
    设置为 0 以禁用。
rcon.password:
  default: ""
  description: "rcon 服务器所使用的密码。"
rcon.port:
  default: "25575"
  description: "在服务器上启用 rcon 时，rcon 服务器所绑定的端口。"
region-file-compression:
  default: "deflate"
  description: >
    指定压缩块(region)文件所用的压缩方式。可指定值为 "deflate", "lz4" 或 "none"。
    如果设置为 "none"，块文件将占用更多的磁盘空间，但与文件系统级的压缩一起使用可能会使其更有意义。
require-resource-pack:
  default: "false"
  description: "如果本项为 true，客户端必须下载服务器资源包才能连接到服务器。否则客户端将被踢出服务器。"
resource-pack:
  default: ""
  description: "服务器资源包的 URL。"
resource-pack-id:
  default: ""
  description: "服务器所使用的资源包的 UUID。"
resource-pack-prompt:
  default: ""
  description: "当客户端提醒需要下载资源包时显示的提示信息。"
resource-pack-sha1:
  default: ""
  description: >
    资源包的哈希值。建议设置该项以使玩家下载正确的资源包。
server-ip:
  default: ""
  description: "服务器绑定到的 IP 地址。留空向全局广播。"
server-port:
  default: "25565"
  description: "连接到服务器的端口。"
simulation-distance:
  default: "10"
  description: >
    能够被服务端运算的实体与玩家之间的最大距离，其将在玩家的各个方向上检测。(以半径而非直径计算)
    如果实体超出此半径，则服务器不会对其进行运算，玩家也不会看见这些实体。
    这个数值应介于 3 到 32 之间。
spawn-monsters:
  default: "true"
  description: "是否生成怪物。"
spawn-protection:
  default: "16"
  description: >
    决定出生点保护范围的边长，长度为 2x+1。设定值为 1 时将会使其**边长为 3**。
    将其设定为 0 以禁用出生点保护。如若启用，数值必须是大于 1 的整数。
sync-chunk-writes:
  default: "true"
  description: |
    启用异步写入区块数据。在 Paper 上这默认是无效的，除非[对应的设置](/paper/reference/system-properties#paperenable-sync-chunk-writes)被设置为 true。
text-filtering-config:
  default: ""
  description: "指定的文本过滤配置文件的路径。留空禁用本配置项。"
text-filtering-version:
  default: "0"
  description: |
    为 [`text-filtering-config`](#text_filtering_config) 指定的配置格式。
    有效值为 0 或 1。
use-native-transport:
  default: "true"
  description: "此选项可以为 Linux 服务器带来性能提升。"
view-distance:
  default: "10"
  description: >
    设置服务器向客户端发送的世界数据量，以玩家为中心，以区块为单位测量每个方向的范围（半径，而非直径）。它决定了服务器端的可视距离（默认值：10，最小值：3，最大值：32）。
white-list:
  default: "false"
  description: "在服务器上启用白名单。启用后，只有在白名单中的玩家才能连接到服务器。"
