advancements:
  disable-saving:
    default: "false"
    description: 防止保存进度。
  disabled:
    default: "[minecraft:story/disabled]"
    description: >-
      一系列的字符串。分别是:

      - 一个包括了命名空间的成绩名称。比如输入 "minecraft:adventure/avoid_vibration"，将会禁用
      "潜行100级" 这个进度。[Minecraft 维基](https://zh.minecraft.wiki/w/%E8%BF%9B%E5%BA%A6#%E8%BF%9B%E5%BA%A6%E5%88%97%E8%A1%A8)
      有所有的原版进度名称。实际使用时需要在它们的前面加上一个 "minecraft:" 命名空间前缀。

      - 一个 "*"。这会禁用*所有*的进度。

      - 一个进度标签的命名空间。比如说输入 "minecraft" 将会禁用所有其包含的进度。


      当父进度被禁用而子进度未被禁用，将会引发异常。
commands:
  log:
    default: "true"
    description: >-
      玩家使用命令时是否记录。这将会_马上_通过 "<playername> issued server command:
      <command>" 的格式记录。
  replace-commands:
    default: "[setblock,summon,testforblock,tellraw]"
    description: 一个包含了原版治疗的列表。列表中的指令将不会被任何其他插件覆盖为插件指令。
  send-namespaced:
    default: "true"
    description: >-
      命令补全时，是否发送带有命名空间的命令到客户端。
  silent-commandblock-console:
    default: "false"
    description: 是否记录原版指令的实行结果到控制台。
  spam-exclusions:
    default: "[/skill]"
    description: >-
      任何信息，或者命令前带有在这个列表之内的前缀，将会被内建的反刷屏系统忽略。

      命令需要加一个 "/" 前缀才会被识别为命令。
  tab-complete:
    default: "0"
    description: >-
      在使用制表键补全(Tab-complete)时需要输入的字符数量。

      - < 0: 禁用补全。

      - = 0: 总是补全所有可用命令。

      - \\> 0 : 需要输入指定的字符数量之后才能补全。由于客户端的代码变动，这没有实际作用。
messages:
  outdated-client:
    default: "Outdated client! Please use {0}"
    description: >-
      客户端版本过旧无法连接到服务器时显示的信息。

      这条字符串使用在某个字符之前加 "&" 的方式添加效果("&" style formatting)，通过添加 "\\n" 来另起一行。
      另外，{0} 这个占位符指代 "%%_MAJ_MIN_PAT_MC_%%" (目前的服务端版本)。

      由于 "&" style formatting 这个词过于实在无法通过一种简明的方式翻译为中文，笔者在此处给出例子。
      比如 "&c" 代表把之后的字符变为红色，"&l" 代表加粗，"&r" 代表重置所有效果。
  outdated-server:
    default: "Outdated server! I'm still on {0}"
    description: >-
      服务端版本过旧无法连接到服务器时显示的信息。

      这条字符串使用在某个字符之前加 "&" 的方式添加效果("&" style formatting)，通过添加 "\\n" 来另起一行。
      另外，{0} 这个占位符指代 "%%_MAJ_MIN_PAT_MC_%%" (目前的服务端版本)。
      "&" style formatting 的具体解释可参见本文档内 "outdated-client" 一项。
  restart:
    default: Server is restarting
    description: >-
      当服务器正在重启时，玩家试图登录服务器时看到的消息。

      这条字符串使用在某个字符之前加 "&" 的方式添加效果("&" style formatting)，通过添加 "\\n" 来另起一行。
      "&" style formatting 的具体解释可参见本文档内 "outdated-client" 一项。
  server-full:
    default: The server is full!
    description: >-
      当服务器满员时，玩家试图登录服务器时看到的消息。

      这条字符串使用在某个字符之前加 "&" 的方式添加效果("&" style formatting)，通过添加 "\\n" 来另起一行。
      "&" style formatting 的具体解释可参见本文档内 "outdated-client" 一项。
  unknown-command:
    default: Unknown command. Type "/help" for help.
    description: >-
      当玩家输入了一个在服务端上无法找到的命令时，玩家看到的消息。

      这条字符串使用在某个字符之前加 "&" 的方式添加效果("&" style formatting)，通过添加 "\\n" 来另起一行。
      "&" style formatting 的具体解释可参见本文档内 "outdated-client" 一项。
  whitelist:
    default: You are not whitelisted on this server!
    description: >-
      这条消息会在以下情况下向客户端发送:

      - 当白名单启动时，不在白名单上的玩家试图登录服务器。

      - 当玩家从白名单上被移除且 enforce-whitelist 项启用时。
      
      - 当启动白名单时且 enforce-whitelist 项启用时，不在白名单上的玩家在服务器内。


      这条字符串使用在某个字符之前加 "&" 的方式添加效果("&" style formatting)，通过添加 "\\n" 来另起一行。
      "&" style formatting 的具体解释可参见本文档内 "outdated-client" 一项。
players:
  disable-saving:
    default: "false"
    description: 禁止保存玩家数据。
settings:
  attribute:
    attackDamage:
      max:
        default: "2048.0"
        description: 覆写最大伤害(attackDamage)的属性最大值。
    maxAbsorption:
      max:
        default: "2048.0"
        description: 覆写最大伤害吸收(maxAbsorption)的属性最大值。
    maxHealth:
      max:
        default: "1024.0"
        description: 覆写最大生命(maxHealth)的属性最大值。
    movementSpeed:
      max:
        default: "1024.0"
        description: 覆写最大移动速度(movementSpeed)的属性最大值。
  bungeecord:
    default: "false"
    description: |-
      启用对 BungeeCord 的支持。这会:
      - 接收转发的玩家数据和客户端 IP 地址。
      - 支持绑定到Unix域套接字(Unix domain socket，也即，本地套接字)。
      
      关于本地套接字参见 [UDS](https://en.wikipedia.org/wiki/Unix_domain_socket)。
      所有中文维基对于 Unix 域套接字的翻译都不是很全面，因此笔者在此处贴了英文维基。
  debug:
    default: "false"
    description: "启动调试模式。这将会把所有的报告等级设定为 ALL。"
  log-named-deaths:
    default: "true"
    description: >-
      是否把带有名字的实体的死亡信息记录到控制台和 latest.log。
  log-villager-deaths:
    default: "true"
    description: >-
      是否把村民的死亡信息记录到控制台和 latest.log。
  moved-too-quickly-multiplier:
    default: "10.0"
    description: >-
      决定在一个包内玩家的移动速度。如果超过此值，那么服务端将会记录
      并且会试图将玩家回弹到上一个位置。
  moved-wrongly-threshold:
    default: "0.0625"
    description: >-
      决定在一个包内玩家的移动速度，取决于玩家当前加载的区块。如果超过此阈值，那么服务端将会记录
      并且会试图将玩家回弹到上一个位置。
  netty-threads:
    default: "4"
    description: 设置 netty 线程的数量。
  player-shuffle:
    default: "0"
    description: >-
      刷新玩家连接列表的频率，以刻为单位。设置为 0 或更小则禁用。
      这将防止玩家为了提升他们在刻顺序中的位置而*策略性*地重新登录。
      如果这个值值较低可能会对性能产生影响。
  restart-on-crash:
    default: "true"
    description: >-
      当服务器被监视进程杀死时，是否拉起 \`restart-script\` 。
      提示: 当被外部力量结束进程，比如说操作系统的任务管理器，其将不会被拉起。
  restart-script:
    default: ./start.sh
    description: >-
      服务器重启时候执行的脚本。

      - 在 Windows 上这等同于 \`cmd /c start {restart-script}\`。
      这意味着需要指定一个批处理文件(*.bat)作为脚本。请参阅 [微软的文档](https://learn.microsoft.com/zh-cn/windows-server/administration/windows-commands/start)
      以使用指定的选项启动。
      笔者推荐参阅英文原版，因为中文为机翻。

      - 在其他平台上等同于 \`sh {restart-script}\`。
      这意味着需要通过绝对或相对路径指定一个 shell 脚本(*.sh)。
      参阅你使用的操作系统的文档以了解如何使用脚本。
      (例: [Man Pages](https://man.archlinux.org/man/sh.1p#command_file))


      了解更多信息，参阅[此处](https://gist.github.com/Prof-Bloodstone/6367eb4016eaf9d1646a88772cdbbac5).
  sample-count:
    default: "12"
    description: >-
      决定在光标悬浮到玩家数量位置时，返回的玩家数量。
      顺序和选中的玩家是随机的。
  save-user-cache-on-stop-only:
    default: "false"
    description: "如果为 false，那么服务器在每次更新的时候都会保存一次玩家缓存。"
  timeout-time:
    default: "60"
    description: >-
      刻与刻运算之间允许相差的最大时间，以秒作为单位。
      如果超过该阈值将会杀死服务端进程。
  user-cache-size:
    default: "1000"
    description: 玩家缓存内保存到最大玩家数量。
stats:
  disable-saving:
    default: "false"
    description: 是否阻止保存服务器指标数据。
  forced-stats:
    default: "{}"
    description: >-
      一个对象。它需要满足如下条件:

      - 任何的统计信息命名空间ID。可以在 [Minecraft 维基](https://zh.minecraft.wiki/w/%E7%BB%9F%E8%AE%A1%E4%BF%A1%E6%81%AF#%E7%BB%9F%E8%AE%A1%E4%BF%A1%E6%81%AF%E5%88%97%E8%A1%A8) 的对应处查阅。

      - 每个键的值都是一个整数，用于强制指定相关统计数据。
world-settings:
  default:
    unload-frozen-chunks:
      default: "false"
      description: 实验性选项。通过 /tick freeze 冻结刻时，是否可以卸载区块。
    arrow-despawn-rate:
      default: "1200"
      description: 箭矢消失之前经过的游戏刻。
    below-zero-generation-in-existing-chunks:
      default: "true"
      description: >-
        是否将所有原有区块内的高度转换为 1.18 之后的完整高度。
    dragon-death-sound-radius:
      default: "0"
      description: >-
        决定末影龙死亡时音效的播放半径。
        如果为 0，则音效会对所有维度内的所有玩家播放。
    enable-zombie-pigmen-portal-spawns:
      default: "true"
      description: >-
        是否允许下界传送门生成僵尸猪灵。
        通过传送门传送的生物不受影响。
    end-portal-sound-radius:
      default: "0"
      description: >-
        末地传送门激活时音效的播放半径。
        如果为 0，则音效会对所有维度内的所有玩家播放。
    entity-activation-range:
      animals:
        default: "32"
        description: 动物实体的激活范围。
      flying-monsters:
        default: "32"
        description: 可飞行怪物的实体激活范围。
      ignore-spectators:
        default: "false"
        description: 旁观者是否可以激活周围的生物。
      misc:
        default: "16"
        description: 杂项实体的激活范围。
      monsters:
        default: "32"
        description: 怪物的实体激活范围。
      raiders:
        default: "64"
        description: 掠夺者的实体激活范围。
      tick-inactive-villagers:
        default: "true"
        description: >-
          是否持续对激活范围之外的村民实体进行刻运算。
      villagers:
        default: "32"
        description: 村民的实体激活范围。
      villagers-active-for-panic:
        default: "true"
        description: 当村民进入恐慌时是否激活实体。
      villagers-work-immunity-after:
        default: "100"
        description: >-
          村民必须处于非活动状态并工作才能进入活跃状态的时间（以刻为单位）。
      villagers-work-immunity-for:
        default: "20"
        description: >-
          villagers-work-immunity-after 的时间之后，村民能够被活跃多长时间（以刻为单位）。
      wake-up-inactive:
        animals-every:
          default: "1200"
          description: >-
            范围外不活跃动物被唤醒的频率（以刻为单位）。由于 animals-max-per-tick 的限制，此值为最小值。
        animals-for:
          default: "100"
          description: "唤醒一个不活跃动物所需时间，以刻为单位。"
        animals-max-per-tick:
          default: "4"
          description: >-
            同一游戏刻内最多可以唤醒的不活跃动物数量。
        flying-monsters-every:
          default: "200"
          description: >-
            范围外不活跃可飞行怪物被唤醒的频率（以刻为单位）。由于
            flying-monsters-max-per-tick 的限制，此值为最小值。
        flying-monsters-for:
          default: "100"
          description: "唤醒一个不活跃的可飞行怪物所需时间，以刻为单位。"
        flying-monsters-max-per-tick:
          default: "8"
          description: >-
            同一游戏刻内最多可以唤醒的不活跃的可飞行怪物数量。
        monsters-every:
          default: "400"
          description: >-
            范围外不活跃的怪物被唤醒的频率（以刻为单位）。由于
            monsters-max-per-tick 的限制，此值为最小值。
        monsters-for:
          default: "100"
          description: "唤醒一个不活跃的怪物所需时间，以刻为单位。"
        monsters-max-per-tick:
          default: "8"
          description: >-
            同一游戏刻内最多可以唤醒的不活跃的怪物数量。
        villagers-every:
          default: "600"
          description: >-
            范围外不活跃村民被唤醒的频率（以刻为单位）。由于
            villagers-max-per-tick 的限制，此值为最小值。
        villagers-for:
          default: "100"
          description: "唤醒一个不活跃的村民所需时间，以刻为单位。"
        villagers-max-per-tick:
          default: "4"
          description: >-
            同一游戏刻内最多可以唤醒的不活跃的村民数量。
      water:
        default: "16"
        description: 水下实体被激活的范围。
    entity-tracking-range:
      animals:
        default: "96"
        description: >-
          控制多少格范围内的动物实体将会被发送给玩家。
          这会被 [entity-broadcast-range-percentage](/paper/reference/server-properties#entity_broadcast_range_percentage) 倍乘。
      display:
        default: "128"
        description: >-
          控制多少格范围内的显示实体(display entity)将会被发送给玩家。
          这会被 [entity-broadcast-range-percentage](/paper/reference/server-properties#entity_broadcast_range_percentage) 倍乘。
      misc:
        default: "96"
        description: >-
          控制多少格范围内的杂类实体将会被发送给玩家。
          这会被 [entity-broadcast-range-percentage](/paper/reference/server-properties#entity_broadcast_range_percentage) 倍乘。
      monsters:
        default: "96"
        description: >-
          控制多少格范围内的怪物实体将会被发送给玩家。
          这会被 [entity-broadcast-range-percentage](/paper/reference/server-properties#entity_broadcast_range_percentage) 倍乘。
      other:
        default: "64"
        description: >-
          控制多少格范围内的方块实体将会被发送给玩家。
          这会被 [entity-broadcast-range-percentage](/paper/reference/server-properties#entity_broadcast_range_percentage) 倍乘。
      players:
        default: "128"
        description: >-
          控制多少格范围内的方块将会被发送给玩家。
          这会被 [entity-broadcast-range-percentage](/paper/reference/server-properties#entity_broadcast_range_percentage) 倍乘。
    growth:
      bamboo-modifier:
        default: "100"
        description: >-
          竹子的生长速率百分比。作为对照，原版的速率为 100%。
          本配置项无法禁止其生长，默认最小为 100%。

          最大生长倍率为 300%。
      beetroot-modifier:
        default: "100"
        description: >-
          甜菜根的生长速率百分比。作为对照，原版的速率为 100%。
          本配置项无法禁止其生长，默认最小为 100%。

          最大生长倍率为 5100%。
      cactus-modifier:
        default: "100"
        description: >-
          仙人掌的生长速率百分比。作为对照，原版的速率为 100%。
          本配置项无法禁止其生长，默认最小为 100%。

          最大生长倍率为 1600%。
      cane-modifier:
        default: "100"
        description: >-
          甘蔗的生长速率百分比。作为对照，原版的速率为 100%。
          本配置项无法禁止其生长，默认最小为 100%。

          最大生长倍率为 1600%。
      carrot-modifier:
        default: "100"
        description: >-
          胡萝卜的生长速率百分比。作为对照，原版的速率为 100%。
          本配置项无法禁止其生长，默认最小为 100%。

          最大生长倍率为 5100%。
      cavevines-modifier:
        default: "100"
        description: >-
          洞穴藤蔓的生长速率百分比。作为对照，原版的速率为 100%。
          本配置项无法禁止其生长，默认最小为 100%。

          最大生长倍率为 1000%。
      cocoa-modifier:
        default: "100"
        description: >-
          可可豆的生长速率百分比。作为对照，原版的速率为 100%。
          本配置项无法禁止其生长，默认最小为 100%。

          最大生长倍率为 500%。
      glowberry-modifier:
        default: "100"
        description: >-
          发光浆果的生长速率百分比。作为对照，原版的速率为 100%。
          本配置项无法禁止其生长，默认最小为 100%。

          最大生长倍率大概是 910%。
      kelp-modifier:
        default: "100"
        description: >-
          海带的生长速率百分比。作为对照，原版的速率为 100%。
          本配置项无法禁止其生长，默认最小为 100%。

          最大生长倍率大概是 715%。
      melon-modifier:
        default: "100"
        description: >-
          西瓜的生长速率百分比。作为对照，原版的速率为 100%。
          本配置项无法禁止其生长，默认最小为 100%。

          最大生长倍率为 5100%。
      mushroom-modifier:
        default: "100"
        description: >-
          蘑菇的生长速率百分比。作为对照，原版的速率为 100%。
          本配置项无法禁止其生长，默认最小为 100%。

          最大生长倍率为 2500%。
      netherwart-modifier:
        default: "100"
        description: >-
          地狱疣的生长速率百分比。作为对照，原版的速率为 100%。
          本配置项无法禁止其生长，默认最小为 100%。

          最大生长倍率为 1000%。
      pitcherplant-modifier:
        default: "100"
        description: >-
          瓶子草荚果的生长速率百分比。作为对照，原版的速率为 100%。
          本配置项无法禁止其生长，默认最小为 100%。

          最大生长倍率为 5100%。
      potato-modifier:
        default: "100"
        description: >-
          土豆的生长速率百分比。作为对照，原版的速率为 100%。
          本配置项无法禁止其生长，默认最小为 100%。

          最大生长倍率为 5100%。
      pumpkin-modifier:
        default: "100"
        description: >-
          南瓜的生长速率百分比。作为对照，原版的速率为 100%。
          本配置项无法禁止其生长，默认最小为 100%。

          最大生长倍率为 5100%。
      sapling-modifier:
        default: "100"
        description: >-
          树苗的生长速率百分比。作为对照，原版的速率为 100%。
          本配置项无法禁止其生长，默认最小为 100%。

          最大生长倍率为 700%。
      sweetberry-modifier:
        default: "100"
        description: >-
          甜浆果的生长速率百分比。作为对照，原版的速率为 100%。
          本配置项无法禁止其生长，默认最小为 100%。

          最大生长倍率为 500%。
      torchflower-modifier:
        default: "100"
        description: >-
          火把花的生长速率百分比。作为对照，原版的速率为 100%。
          本配置项无法禁止其生长，默认最小为 100%。

          最大生长倍率为 5100%。
      twistingvines-modifier:
        default: "100"
        description: >-
          缠怨藤的生长速率百分比。作为对照，原版的速率为 100%。
          本配置项无法禁止其生长，默认最小为 100%。

          最大生长倍率为 1000%。
      vine-modifier:
        default: "100"
        description: >-
          藤蔓的生长速率百分比。作为对照，原版的速率为 100%。
          本配置项无法禁止其生长，默认最小为 100%。

          最大生长倍率为 400%。
      weepingvines-modifier:
        default: "100"
        description: >-
          垂泪藤的生长速率百分比。作为对照，原版的速率为 100%。
          本配置项无法禁止其生长，默认最小为 100%。

          最大生长倍率为 1000%。
      wheat-modifier:
        default: "100"
        description: >-
          小麦的生长速率百分比。作为对照，原版的速率为 100%。
          本配置项无法禁止其生长，默认最小为 100%。

          最大生长倍率为 5100%。
    hanging-tick-frequency:
      default: "100"
      description: "悬挂实体(比如画和物品展示框)应该在多少游戏刻内运算一次。"
    hopper-amount:
      default: "1"
      description: "漏斗一次性能搬运多少物品。"
    hopper-can-load-chunks:
      default: "false"
      description: Whether to prevent hoppers from loading chunks.
    hunger:
      combat-exhaustion:
        default: "0.1"
        description: 攻击时饱食度的消耗倍率。
      jump-sprint-exhaustion:
        default: "0.2"
        description: 跑跳时饱食度的消耗倍率。
      jump-walk-exhaustion:
        default: "0.05"
        description: 走跳时饱食度的消耗倍率。
      other-multiplier:
        default: "0.0"
        description: 爬行(陆游)，潜行，正常走路时饱食度的消耗倍率。
      regen-exhaustion:
        default: "6.0"
        description: 恢复生命的时恢复多少饱食度。
      sprint-multiplier:
        default: "0.1"
        description: 冲刺时饱食度的消耗倍率。
      swim-multiplier:
        default: "0.01"
        description: >-
          当玩家正在"游泳"的时候饱食度的消耗倍率。这里的游泳，包括:

          - 真的在游泳

          - 水下行走(眼睛在水下)

          - 水上行走(眼睛在水上)
    item-despawn-rate:
      default: "6000"
      description: >-
        物品消失之前的最大存活时间。单独的配置项需要参看 Paper 配置文件内的 [per-world
        config](/paper/reference/world-configuration#entities_spawning_alt_item_despawn_rate) 。
    max-tick-time:
      entity:
        default: "50"
        description: "此配置项不起作用，并且这是一条没有任何作用的上游配置项。"
      tile:
        default: "50"
        description: "由于 Paper 修复了这个特性，这条配置项没有任何作用。"
    max-tnt-per-tick:
      default: "100"
      description: 服务器每刻允许处理的最大 TNT 数量。设置为 0 禁用。
    merge-radius:
      exp:
        default: "-1"
        description: >-
          经验球之间相距多少距离才会合并为更大的经验球
          在原版中这项特性不存在。设置为 0 或更小的值来禁用这条配置项。
      item:
        default: "0.5"
        description: "物品与物品之间能够堆叠的最小半径。"
    mob-spawn-range:
      default: "8"
      description: "玩家周围多少区块之内可以生成生物。"
    nerf-spawner-mobs:
      default: "false"
      description: 对刷怪笼生成的生物禁用大部分 AI。
    seed-ancientcity:
      default: "20083232"
      description: 古城的结构种子。
    seed-buriedtreasure:
      default: "10387320"
      description: 埋藏的宝藏的结构种子。
    seed-desert:
      default: "14357617"
      description: 沙漠结构的生成种子。
    seed-endcity:
      default: "10387313"
      description: 末地城的结构种子。
    seed-fossil:
      default: "14357921"
      description: 化石的结构种子。
    seed-igloo:
      default: "14357618"
      description: 雪屋的结构种子。
    seed-jungle:
      default: "14357619"
      description: 丛林结构的生成种子。
    seed-mansion:
      default: "10387319"
      description: 林地府邸的结构种子。
    seed-mineshaft:
      default: default
      description: 废弃矿井的结构种子。
    seed-monument:
      default: "10387313"
      description: 海洋神殿的结构种子。
    seed-nether:
      default: "30084232"
      description: 下界结构的生成种子。
    seed-ocean:
      default: "14357621"
      description: 海洋结构的生成种子。
    seed-outpost:
      default: "165745296"
      description: 前哨站的结构种子。
    seed-portal:
      default: "34222645"
      description: 传送门的结构种子。
    seed-shipwreck:
      default: "165745295"
      description: 沉船的结构种子。
    seed-slime:
      default: "987234911"
      description: 史莱姆区块的生成种子。
    seed-stronghold:
      default: default
      description: 要塞的结构种子。
    seed-swamp:
      default: "14357620"
      description: 沼泽小屋的结构种子。
    seed-trialchambers:
      default: "94251327"
      description: 试炼密室的结构种子。
    seed-trailruins:
      default: "83469867"
      description: 试炼遗迹的结构种子。
    seed-village:
      default: "10387312"
      description: 村庄的结构种子。
    simulation-distance:
      default: default
      description: >-
        覆写模拟距离。设置为 -1 或 "default" 使用 [server.properties](/paper/reference/server-properties#simulation_distance)
        里的对应值。
    thunder-chance:
      default: "100000"
      description: >-
        在雷雨期间生成闪电的可能性。
        概率为 1/<配置的数值> ，每个区块每个游戏刻单独检测。
    ticks-per:
      hopper-check:
        default: "1"
        description: 从另外一个容器内获取物品检测的间隔时间。
      hopper-transfer:
        default: "8"
        description: 漏斗内物品的运送速度。
    trident-despawn-rate:
      default: "1200"
      description: 三叉戟实体的存活时间。
    verbose:
      default: "false"
      description: >-
        是否在加载配置文件时输出所有的世界选项。
        这会在你使用 \`/spigot reload\` 或者 \`/reload\` 的时候发生。
    view-distance:
      default: default
      description: >-
        覆写视距。设置为 -1 或 "default" 使用 [server.properties](/paper/reference/server-properties#view_distance)
        的对应值。
    wither-spawn-sound-radius:
      default: "0"
      description: >-
        决定凋零生成时候音效的播放半径。如果为0，则音效会对所有玩家播放。
    zombie-aggressive-towards-villager:
      default: "true"
      description: "僵尸是否应该对村民表现出攻击性。"
config-version:
  default: ""
  description: "在升级配置文件的时候自动生成的一个常量。**不要修改它。**"
